service: serverless-ts-app

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: dist/handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
